apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nginx-with-vault.fullname" . }}
  labels:
    {{- include "nginx-with-vault.labels" . | nindent 4 }}
type: Opaque
data:
  secret: <path:admin/secret/sample-secret#first-secret>