apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nginx-with-vault.fullname" . }}
  labels:
    {{- include "nginx-with-vault.labels" . | nindent 4 }}
type: Opaque
data:
  secret: "<path:kc-development-vaut#stmp-uri | base64encode>"
  value: {{ .Values.custom | b64enc }}
  db: {{ .Values.kratos.database.databaseSecretName | b64enc }}
  d2: {{ .Values.kratos.database.databaseSecretName | b64enc }}