apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nginx-with-vault.fullname" . }}
  labels:
    {{- include "nginx-with-vault.labels" . | nindent 4 }}
stringData:
  secret: "<path:admin/secret/sample-secret#second-secret>"